lib{nuklear}: h{**}

# Build options.
#
c.poptions =+ "-I$src_root"

# Export options.
#
lib{nuklear}:
{
  c.export.poptions = "-I$src_root"
}

# Install into the nuklear/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/nuklear/
}
