intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{nuklear}: h{**} $intf_libs

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{nuklear}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $intf_libs
}

# Install into the libnuklear/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/libnuklear/
  install.subdirs = true
}
